FROM openjdk:11-jdk-slim
# Install wget
RUN apt-get update && apt-get install -y wget
RUN wget -O activemq.tar.gz http://archive.apache.org/dist/activemq/5.17.6/apache-activemq-5.17.6-bin.tar.gz 
RUN tar -xzf activemq.tar.gz 
CMD ["apache-activemq-5.17.6/bin/activemq", "console"]